version: '2'
services:
  kosmtik:
    image: kosmtik:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/openstreetmap-carto
    depends_on:
      - db
      - nginx
    ports:
      - "6789:6789"
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - MBTILES_FILE=/openstreetmap-carto/data/svg.mbtiles
      - MBTILES_X_MIN=-61.705
      - MBTILES_Y_MIN=12.568
      - MBTILES_X_MAX=-60.712
      - MBTILES_Y_MAX=13.626
      - MBTILES_MIN_ZOOM=12
      - MBTILES_MAX_ZOOM=16
  db:
    image: db:v1
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
    volumes:
      - osm-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  import:
    image: import:v1
    build:
      context: .
      dockerfile: Dockerfile.import
    volumes:
      - .:/openstreetmap-carto
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
      - OSM2PGSQL_CACHE
      - OSM2PGSQL_NUMPROC
      - OSM2PGSQL_DATAFILE
  nginx:
    image: nginx
    volumes:
      - ./svg/svg_mbtiles.html:/usr/share/nginx/html/index.html:ro
      - ./data/svg.mbtiles:/usr/share/nginx/html/svg.mbtiles:ro
    ports:
      - "80:80"
volumes:
  osm-pgdata:
    external: true
